
alias grep='grep --color=auto -i'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

## maven
alias mcc='mvn clean compile'
alias mct='mvn clean test'
alias mcit='mvn clean integration-test'
alias mld='mvn clean process-resources liquibase:dropAll'
alias mlu='mvn clean process-resources liquibase:update'
alias mcj='mvn clean jetty:run'

## git
alias gbye='git add --all; git reset --hard HEAD'
alias gs='git status'
alias gb='git branch -a'
alias gma='git commit -am'
alias gmm='git commit -m'
alias gc='git checkout'
alias gcm='git checkout master'
alias ga='git add'
alias gall='git add --all'
alias gp='git pull'

# determine operating system
myos=`uname -s`

case "$myos" in
	# Mac OS X specific aliases
	Darwin)
		alias fnote='find ~/pHome/pNote -type f -name "*.md" | xargs grep -i'
		alias sublime='open -a "Sublime Text 2"'
		alias mou='open -a Mou'
		alias click='open .'
		# virtual box 
		alias pvm='ssh pvm@192.168.56.190'
		alias startpvm='VBoxHeadless -startvm Ubuntu_Server -vrdp=off'
		alias soundsgood='sudo kextunload /System/Library/Extensions/AppleHDA.kext;sudo kextload /System/Library/Extensions/AppleHDA.kext'
		;;
	# Linux
	Linux)
		alias click='nautilus .'
		alias fnote='find ~/pNote -type f -name "*.md" | xargs grep -i'
		alias gstory="git branch -a --no-merged master | sed 's/remotes\/origin\//remotes\/origin\/    /g' | grep 'B-\|D-'"
		# directory
		alias usgroot='cd ~/usage/Usage-Standardization'
		alias solroot='cd ~/usage/sol42Generator'
		alias pnoteroot='cd ~/pNote/notes'
		# command 
		alias amq='/opt/apache-activemq-5.8.0/bin/activemq'
		;;
	*) ;;
esac

